//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XbScaffolder {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XbScaffolder.MessageStrings", typeof(MessageStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   https://github.com/aspnet/Scaffolding/blob/1.1.3/src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/MessageStrings.resx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _Got_This_Code_From_ {
            get {
                return ResourceManager.GetString("_Got_This_Code_From_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AreaName cannot be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaNameRequired {
            get {
                return ResourceManager.GetString("AreaNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Controller Name is required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControllerNameRequired {
            get {
                return ResourceManager.GetString("ControllerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DbContextName cannot be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbContextNameRequired {
            get {
                return ResourceManager.GetString("DbContextNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Controller name is required for an Empty Controller に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmptyControllerNameRequired {
            get {
                return ResourceManager.GetString("EmptyControllerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file {0} exists, use -f option to overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileExists_useforce {
            get {
                return ResourceManager.GetString("FileExists_useforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The namespace name &apos;{0}&apos; is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidNamespaceName {
            get {
                return ResourceManager.GetString("InvalidNamespaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ModelName cannot be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelNameRequired {
            get {
                return ResourceManager.GetString("ModelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a valid {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProvideValidArgument {
            get {
                return ResourceManager.GetString("ProvideValidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There may be additional steps required for the generated code to work. Refer to &lt;forward-link&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scaffolding_additionalSteps {
            get {
                return ResourceManager.GetString("Scaffolding_additionalSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaffolding generated all the code but the new context created could be registered using dependency injection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScaffoldingSuccessful_unregistered {
            get {
                return ResourceManager.GetString("ScaffoldingSuccessful_unregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The TemplateName cannot be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateNameRequired {
            get {
                return ResourceManager.GetString("TemplateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A type with the name {0} does not exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TypeDoesNotExist {
            get {
                return ResourceManager.GetString("TypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validation succeded but model type not set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationSuccessfull_modelUnset {
            get {
                return ResourceManager.GetString("ValidationSuccessfull_modelUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ViewName cannot be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewNameRequired {
            get {
                return ResourceManager.GetString("ViewNameRequired", resourceCulture);
            }
        }
    }
}
